SQH.MapaDeAlocacao/Controllers/AlocacaoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SQH.Business.Contract;
using SQH.Entities.Models.Alocacao;
using SQH.Entities.Requisicao;
using System;
using System.Collections.Generic;
using System.Linq;
using static SQH.Shared.Enums.Alerts;

namespace SQH.MapaDeAlocacao.Controllers
{
    [Authorize]
    public class AlocacaoController : BaseController
    {
        private readonly IAlocacaoRecursoService _alocacaoRecursoService;
        private readonly ITipoAlocacaoService _tipoAlocacaoService;
        private readonly IAlocacaoProjetoService _alocacaoProjetoService;

        public AlocacaoController(IAlocacaoRecursoService alocacaoRecursoService, ITipoAlocacaoService tipoAlocacaoService,
                                    IAlocacaoProjetoService alocacaoProjetoService)
        {
            _alocacaoRecursoService = alocacaoRecursoService;
            _tipoAlocacaoService = tipoAlocacaoService;
            _alocacaoProjetoService = alocacaoProjetoService;
        }

        [HttpPost, Route("CreateAlocacaoRecurso", Name = "AlocacaoRecursoPost")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAlocacaoRecurso(AlocacaoRecursoModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.IdRecurso == 0)
                    {
                        _alocacaoRecursoService.Incluir(model);

                        ExibirMensagem("Recurso cadastrada com sucesso!!", Alert.success);
                    }
                    else
                    {
                        _alocacaoRecursoService.Editar(model);

                        ExibirMensagem("Recurso alterada com sucesso!!", Alert.success);
                    }
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, Alert.danger);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public IActionResult SalvarAlocacaoProjeto(AlocacaoProjetoModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var requisicao = new AlocacaoProjetoRequisicao(model.IdProjeto, model.IdTipoAlocacao, model.DataInicio, model.DataFim);

                    var retorno = _alocacaoProjetoService.IncluirAlocacaoProjeto(requisicao);

                    if (retorno.Valido)
                    {
                        //ExibirMensagem("Alocação incluída com sucesso.", Alert.success);
                        return Json(new { valido = true, mensagem = "Alocação incluída com sucesso." });
                    }
                    else
                    {
                        return Json(new { valido = false, mensagem = retorno.Mensagem });
                    }
                }
                else
                {
                    return Json(new { valido = false, mensagem = "O formulário foi preenchido incorretamente." });
                }
            }
            catch (Exception ex)
            {
                return Json(new { valido = false, mensagem = ex.Message });
            }
        }

        [HttpPost]
        public IActionResult EditarPeriodoAlocacao(AlocacaoProjetoModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var requisicao = new AlocacaoProjetoRequisicao(model.IdAlocacao, model.DataInicio, model.DataFim);

                    _alocacaoProjetoService.AlterarPeriodoAlocacaoProjeto(requisicao);

                    //ExibirMensagem("Período alterado com sucesso.", Alert.success);
                    return Json(new { valido = true, mensagem = "Período alterado com sucesso." });
                }
                else
                {
                    return Json(new { valido = false, mensagem = "O formulário foi preenchido incorretamente." });
                }
            }
            catch (Exception ex)
            {
                return Json(new { valido = false, mensagem = ex.Message });
            }
        }

        public IActionResult Delete(int id, string redirecionar)
        {
            try
            {
                _alocacaoProjetoService.RemoverAlocacao(id);

                ExibirMensagem("Alocação excluída com sucesso.", Alert.success);
                return RedirectToAction("Edit", "Projeto", new { Id = redirecionar });
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, Alert.danger);
                return RedirectToAction("Edit", "Projeto", new { Id = redirecionar });
            }
        }

        [HttpGet]
        public PartialViewResult ObtemModalAlocacaoProjeto(int idProjeto)
        {
            var model = new AlocacaoProjetoModel();
            model.TiposAlocacao = ObtemSelectListTipoAlocacao();

            return PartialView("_modalAdicionarTipoAlocacao", model);
        }

        #region Métodos Privados
        private List<SelectListItem> ObtemSelectListTipoAlocacao()
        {
            var tiposAlocacao = _tipoAlocacaoService.ObtemTodos();

            var retorno = new List<SelectListItem>();

            tiposAlocacao.ToList().ForEach(x => retorno.Add(new SelectListItem()
            {
                Text = x.Nome,
                Value = x.IdTipoAlocacao.ToString()
            }));

            return retorno;
        }
        #endregion
    }
}

SQH.MapaDeAlocacao/Controllers/AlocacaoRecursoController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using SQH.Entities.Models.Alocacao;
using static SQH.Shared.Enums.Alerts;
using SQH.Business.Contract;

namespace SQH.MapaDeAlocacao.Controllers
{
    [Authorize]
    public class AlocacaoRecursoController : BaseController
    {
        private readonly IAlocacaoRecursoService _alocacaoRecursoService;

        public AlocacaoRecursoController(IAlocacaoRecursoService alocacaoRecursoService)
        {
            _alocacaoRecursoService = alocacaoRecursoService;
        }

        public IActionResult Incluir(AlocacaoRecursoModel model)
        {
            try
            {
                var retorno = _alocacaoRecursoService.Incluir(model);

                if (retorno.Valido)
                {
                    //ExibirMensagem("Alocação de recurso salvo com sucesso.", Alert.success);
                    return Json(new { valido = true, mensagem = "Alocação de recurso salvo com sucesso." });
                }
                else
                {
                    return Json(new { valido = false, mensagem = retorno.Mensagem });
                }
            }
            catch (Exception ex)
            {
                return Json(new { valido = false, mensagem = ex.Message });
            }
        }

        public IActionResult Editar(AlocacaoRecursoModel model)
        {
            try
            {
                var retorno = _alocacaoRecursoService.Editar(model);

                if (retorno.Valido)
                {
                    //ExibirMensagem("Alocação de recurso editado com sucesso.", Alert.success);
                    return Json(new { valido = true, mensagem = "Alocação de recurso editado com sucesso." });
                }
                else
                {
                    return Json(new { valido = false, mensagem = retorno.Mensagem });
                }
            }
            catch (Exception ex)
            {
                return Json(new { valido = false, mensagem = ex.Message });
            }
        }

        public IActionResult Delete(string id, string redirecionar)
        {
            try
            {
                var ids = id.Split('-');

                _alocacaoRecursoService.Deletar(Convert.ToInt32(ids[1]), Convert.ToInt32(ids[0]));

                ExibirMensagem("Alocação de recurso excluída com sucesso.", Alert.success);
                return RedirectToAction("Edit", "Projeto", new { Id = redirecionar });
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, Alert.danger);
                return RedirectToAction("Edit", "Projeto", new { Id = redirecionar });
            }
        }
    }
}

SQH.MapaDeAlocacao/Views/Alocacao/_modalAdicionarRecursoAlocacao.cshtml
@model SQH.Entities.Models.Alocacao.AlocacaoRecursoModel

<div class="modal bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="modalSalvarRecursoAlocacao">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Salvar Alocação</h4>
            </div>
            <div class="modal-body">
                <form id="formSalvarRecursoAlocacao" asp-action="Incluir" asp-controller="AlocacaoRecurso" class="form-horizontal" method="post">
                    <div class="alert alert-danger alert-dismissible hide" role="alert" id="alertErroSalvarRecurso">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong id="msgErroSalvarRecurso"></strong>
                    </div>

                    <input type="hidden" id="idAlocacaoRecurso" asp-for="IdAlocacao" />
                    <input type="hidden" id="idProjetoAlocacaoRecurso" asp-for="IdProjeto" />

                    <div class="form-group">
                        <label asp-for="Recurso" class="col-md-2 control-label"></label>
                        <div class="col-md-9">
                            <input asp-for="Recurso" data-min-caracteres="2" data-url-dados="@Url.Action("ObtemAutoCompleteRecurso", "Recurso")" data-id-value="IdRecurso" type="text" class="form-control autocomplete" />
                            <span asp-validation-for="Recurso" class="text-danger"></span>
                            <input type="hidden" asp-for="IdRecurso" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="DataInicioAlocacaoRecurso" class="col-md-2 control-label"></label>
                        <div class="col-md-9">
                            <input asp-for="DataInicioAlocacaoRecurso" type="text" class="form-control data dataInicioAlocacaoRecurso" />
                            <span asp-validation-for="DataInicioAlocacaoRecurso" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="DataFimAlocacaoRecurso" class="col-md-2 control-label"></label>
                        <div class="col-md-9">
                            <input asp-for="DataFimAlocacaoRecurso" type="text" class="form-control data dataFimAlocacaoRecurso" />
                            <span asp-validation-for="DataFimAlocacaoRecurso" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" id="btnCancelarModalRecursoAlocacao" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="button" id="btnSalvarRecursoAlocacao" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

SQH.MapaDeAlocacao/Views/Alocacao/_modalAdicionarTipoAlocacao.cshtml
@model SQH.Entities.Models.Alocacao.AlocacaoProjetoModel

<div class="modal bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="modalSalvarTipoAlocacao">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Salvar Alocação</h4>
            </div>
            <div class="modal-body">
                <form id="formSalvarAlocacaoProjeto" asp-action="SalvarAlocacaoProjeto" asp-controller="Alocacao" class="form-horizontal" method="post">
                    <div class="alert alert-danger alert-dismissible hide" role="alert" id="alertErroSalvarAlocacaoProjeto">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong id="msgErroSalvarAlocacaoProjeto"></strong>
                    </div>
                    
                    <input type="hidden" asp-for="IdProjeto" />
                    <input type="hidden" asp-for="IdAlocacao" />

                    <div class="form-group" id="divCboAlocacao">
                        <label asp-for="IdTipoAlocacao" class="col-md-2 control-label"></label>
                        <div class="col-md-9">
                            <select asp-for="IdTipoAlocacao" asp-items="@Model.TiposAlocacao" class="form-control"></select>
                            <span asp-validation-for="IdTipoAlocacao" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group hide" id="divStrAlocacao">
                        <label class="col-md-2 control-label">Tipo de Alocação</label>
                        <div class="col-md-9">
                            <label class="control-label" id="lblTipoAlocacao"></label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="DataInicio" class="col-md-2 control-label"></label>
                        <div class="col-md-9">
                            <input asp-for="DataInicio" type="text" class="form-control data dataInicioAlocacaoProjeto" />
                            <span asp-validation-for="DataInicio" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="DataFim" class="col-md-2 control-label"></label>
                        <div class="col-md-9">
                            <input asp-for="DataFim" type="text" class="form-control data dataFinalAlocacaoProjeto" />
                            <span asp-validation-for="DataFim" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" id="btnCancelarSalvarAlocacaoProjeto" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="button" id="btnSalvarAlocacaoProjeto" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>