SQH.MapaDeAlocacao/Controllers/MapaAlocacaoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SQH.Business.Contract;
using SQH.Entities.Models.MapaAlocacao;
using SQH.Entities.Response.Alocacao;
using SQH.Entities.Response.Projeto;
using SQH.Entities.Response.Recurso;
using SQH.Shared.Extensions;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace SQH.MapaDeAlocacao.Controllers
{
    [Authorize]
    public class MapaAlocacaoController : Controller
    {
        private readonly IRecursoService _recursoService;
        private readonly ITipoAlocacaoService _tipoAlocacaoService;
        private readonly IProjetoService _projetoService;
        private readonly IAlocacaoProjetoService _alocacaoProjetoService;
        private readonly IAlocacaoRecursoService _alocacaoRecursoService;

        public MapaAlocacaoController(IRecursoService recursoService, ITipoAlocacaoService tipoAlocacaoService, IProjetoService projetoService, IAlocacaoProjetoService alocacaoProjetoService, IAlocacaoRecursoService alocacaoRecursoService)
        {
            _recursoService = recursoService;
            _tipoAlocacaoService = tipoAlocacaoService;
            _projetoService = projetoService;
            _alocacaoProjetoService = alocacaoProjetoService;
            _alocacaoRecursoService = alocacaoRecursoService;
        }

        public ActionResult Index(string mesAno)
        {
            MapaAlocacaoModel model = new MapaAlocacaoModel();

            model.Recurso = _recursoService.Find(x => x.Apropriar == 1).ToList();
            model.TipoAlocacao = _tipoAlocacaoService.ObtemTodos().ToList();
            model.Projetos = _projetoService.ObtemTodos().ToList();

            DateTime endDate;
            DateTime startDate;

            if (String.IsNullOrEmpty(mesAno))
            {
                var hoje = DateTime.Now;
                endDate = hoje.GetLastDateFromCurrentMonth();
                startDate = new DateTime(hoje.Year, hoje.Month, 1);
            }
            else
            {
                var arrayValue = mesAno.Split('/');
                var ano = Convert.ToInt32(arrayValue[1]);
                var mes = Convert.ToInt32(arrayValue[0]);
                endDate = DateExtensions.GetLastDateFromCurrentMonth(mes, ano);
                startDate = new DateTime(ano, mes, 1);
            }

            var intervaloDatas = Enumerable.Range(0, (endDate - startDate).Days + 1).Select(d => startDate.AddDays(d));

            model.Datas = new List<DatasProjetos>();

            foreach (DateTime itemData in intervaloDatas)
            {
                DatasProjetos datasProjetos = new DatasProjetos();

                datasProjetos.DiaSemana = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(CultureInfo.CurrentCulture.DateTimeFormat.GetDayName(itemData.DayOfWeek));
                datasProjetos.Data = String.Format("{0:dd/MM/yyyy}", itemData);
                datasProjetos.ProjetoRecurso = new List<ProjetoRecursoAlocacao>();

                var alocacoes = _alocacaoRecursoService.Find(x => (x.DataInicio <= itemData && x.DataFim >= itemData));

                foreach (RecursoResponse itemRecurso in model.Recurso)
                {
                    ProjetoRecursoAlocacao projetoResponse = new ProjetoRecursoAlocacao();
                    projetoResponse.IdRecurso = itemRecurso.Id;

                    if (itemData.DayOfWeek != DayOfWeek.Sunday && itemData.DayOfWeek != DayOfWeek.Saturday)
                    {
                        var projetoRecurso = alocacoes.FirstOrDefault(x => x.IdRecurso == itemRecurso.Id);

                        if (projetoRecurso != null)
                        {
                            AlocacaoProjetoResponse alocacaoProjetoResponse = _alocacaoProjetoService.ObtemProjetoPorAlocacao(projetoRecurso.IdAlocacao);
                            projetoResponse.IdProjeto = ((alocacaoProjetoResponse != null) ? alocacaoProjetoResponse.IdProjeto : 0);
                            projetoResponse.Cor = ((alocacaoProjetoResponse != null) ? _tipoAlocacaoService.ObterPorId(alocacaoProjetoResponse.IdTipoAlocacao).Cor : "#FFF");
                            projetoResponse.NomeProjeto = ((alocacaoProjetoResponse != null) ? alocacaoProjetoResponse.NomeProjeto : "");
                        }
                    }
                    else
                    {
                        projetoResponse.Cor = "#d8d9d9";
                    }
                    datasProjetos.ProjetoRecurso.Add(projetoResponse);
                }

                model.Datas.Add(datasProjetos);

            }
            return View(model);
        }
    }
}

SQH.MapaDeAlocacao/Controllers/ProjetoController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SQH.Business.Contract;
using SQH.Entities.Models.Projeto;
using SQH.Entities.Models.Alocacao;
using SQH.Entities.Response.Alocacao;
using Microsoft.AspNetCore.Authorization;
using SQH.Entities.Response.AlocacaoRecurso;
using static SQH.Shared.Enums.Alerts;
using System;
using SQH.Entities.Response.Projeto;

namespace SQH.MapaDeAlocacao.Controllers
{
    [Authorize]
    public class ProjetoController : BaseController
    {
        private readonly IProjetoService _projetoService;
        private readonly ITipoAlocacaoService _tipoAlocacaoService;
        private readonly IAlocacaoProjetoService _alocacaoProjetoService;

        public ProjetoController(IProjetoService projetoService, ITipoAlocacaoService tipoAlocacaoService, IAlocacaoProjetoService alocacaoProjetoService)
        {
            _projetoService = projetoService;
            _tipoAlocacaoService = tipoAlocacaoService;
            _alocacaoProjetoService = alocacaoProjetoService;
        }

        public IActionResult Index()
        {
            var projetos = _projetoService.ObtemTodos();

            var model = new List<ProjetoListaModel>();

            projetos.ToList().ForEach(x => model.Add(new ProjetoListaModel()
            {
                IdProjeto = x.IdProjeto,
                IdRecurso = x.IdRecurso,
                Nome = x.Nome,
                Lider = x.Lider
            }));

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var msg = Request.Query["msg"].Count() > 0 ? Request.Query["msg"].ToString() : null;

            var model = PreencheModelProjeto(id);

            if (msg != null)
                ExibirMensagem(msg, Alert.success);

            return View(model); ;
        }

        public IActionResult AtualizarRegistros()
        {
            try
            {
                _projetoService.AtualizarRegistros();

                ExibirMensagem("Registros atualizados com Sucesso.", Alert.success);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, Alert.danger);
                return RedirectToAction("Index");
            }
        }

        #region Métodos Privados
        private IEnumerable<AlocacaoProjetoResponse> ObtemAlocacoesProjeto(int idProjeto)
        {
            var alocacoesProjeto = _alocacaoProjetoService.ObtemAlocacoesPorProjeto(idProjeto);

            return alocacoesProjeto;
        }

        private ProjetoModel PreencheModelProjeto(int idProjeto)
        {
            var model = new ProjetoModel();

            var projeto = ObtemProjeto(idProjeto);
            var alocacoesProjeto = ObtemAlocacoesProjeto(idProjeto);
            
            model.Id = idProjeto;
            model.Nome = projeto.Nome;

            alocacoesProjeto.ToList().ForEach(x => model.Alocacoes.Add(new AlocacaoProjetoModel()
            {
                DataFim = x.DataFim,
                DataInicio = x.DataInicio,
                IdAlocacao = x.IdAlocacao,
                IdProjeto = x.IdProjeto,
                IdTipoAlocacao = x.IdTipoAlocacao,
                TipoAlocacao = x.TipoAlocacao,
                Recursos = TransformaAlocacaoRecursoModel(x.Recursos)
            }));

            return model;
        }

        private List<AlocacaoRecursoModel> TransformaAlocacaoRecursoModel(IEnumerable<AlocacaoRecursoResponse> response)
        {
            var retorno = new List<AlocacaoRecursoModel>();

            response.ToList().ForEach(x => retorno.Add(new AlocacaoRecursoModel()
            {
                DataFimAlocacaoRecurso = x.DataFim,
                DataInicioAlocacaoRecurso = x.DataInicio,
                IdAlocacao = x.IdAlocacao,
                IdRecurso = x.IdRecurso,
                Recurso = x.Recurso
            }));

            return retorno;
        }

        private ProjetoResponse ObtemProjeto(int id)
        {
            return _projetoService.ObtemPorId(id);
        }
        #endregion
    }
}

SQH.MapaDeAlocacao/Controllers/RecursoController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SQH.Entities.Models.Recurso;
using SQH.Business.Contract;
using static SQH.Shared.Enums.Alerts;
using System;
using Microsoft.AspNetCore.Authorization;
using SQH.Entities.Models;

namespace SQH.MapaDeAlocacao.Controllers
{
    [Authorize]
    public class RecursoController : BaseController
    {
        private readonly IRecursoService _recursoService;

        public RecursoController(IRecursoService recursoService)
        {
            _recursoService = recursoService;
        }

        public IActionResult Index()
        {
            var model = new List<RecursoListaModel>();

            var objs = _recursoService.ObtemTodos();

            objs.ToList().ForEach(x => model.Add(new RecursoListaModel()
            {
                Id = x.Id,
                Nome = x.Nome,
                Email = x.Email
            }));

            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(RecursoModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _recursoService.Incluir(model);

                    ExibirMensagem("Registro incluído com Sucesso.", Alert.success);

                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, Alert.danger);
                return View();
            }
        }

        public IActionResult Edit(int id)
        {
            var obj = _recursoService.ObterPorId(id);
            var viewModel = new RecursoModel()
            {
                Id = obj.IdRecurso,
                Nome = obj.Nome
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(RecursoModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _recursoService.Editar(model);
                    ExibirMensagem("Registro alterado com Sucesso.", Alert.success);

                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, Alert.danger);
                return View();
            }
        }

        public IActionResult Delete(int id)
        {
            try
            {
                _recursoService.Deletar(id);
                ExibirMensagem("Registro excluído com Sucesso.", Alert.success);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, Alert.danger);
                return RedirectToAction("Index");
            }
        }

        public IActionResult AtualizarRegistros()
        {
            try
            {
                _recursoService.AtualizarRegistros();

                ExibirMensagem("Registros atualizados com Sucesso.", Alert.success);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, Alert.danger);
                return RedirectToAction("Index");
            }
        }

        public JsonResult ObtemAutoCompleteRecurso(string termos)
        {
            var recursos = _recursoService.ObtemRecursosPorNome(termos.Trim());

            var retorno = new List<AutoCompleteModel>();

            recursos.ToList().ForEach(x => retorno.Add(new AutoCompleteModel()
            {
                label = x.Nome,
                value = x.Id.ToString()
            }));

            return Json(retorno);
        }
    }
}

SQH.MapaDeAlocacao/Controllers/TipoAlocacaoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using SQH.Business.Contract;
using SQH.Entities.Models.TipoAlocacao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static SQH.Shared.Enums.Alerts;

namespace SQH.MapaDeAlocacao.Controllers
{

    public class TipoAlocacaoController : BaseController
    {
        private readonly ITipoAlocacaoService _tipoAlocacaoService;


        public TipoAlocacaoController(ITipoAlocacaoService tipoAlocacaoService)
        {
            _tipoAlocacaoService = tipoAlocacaoService;
        }

        [Route("tipoAlocacao")]
        public IActionResult Index()
        {
            var model = new List<TipoAlocacaoModel>();

            var objs = _tipoAlocacaoService.ObtemTodos();

            objs.ToList().ForEach(x => model.Add(new TipoAlocacaoModel()
            {
                IdTipoAlocacao = x.IdTipoAlocacao,
                Nome = x.Nome,
                Cor = x.Cor,
                Sigla = x.Sigla
            }));
            return View(model);
        }

        [Route("tipoalocacao/create/{Id=0}", Name = "GetTipoAlocacao")]
        public IActionResult Create(Int32 Id)
        {
            var tipoAlocacao = _tipoAlocacaoService.ObterPorId(Id);
            TipoAlocacaoModel tipoAlocacaoModel = new TipoAlocacaoModel();

            if (tipoAlocacao != null)
            {

                tipoAlocacaoModel = new TipoAlocacaoModel()
                {
                    Cor = tipoAlocacao.Cor,
                    DataCadastro = tipoAlocacao.DataCadastro,
                    IdTipoAlocacao = tipoAlocacao.IdTipoAlocacao,
                    Nome = tipoAlocacao.Nome,
                    Sigla = tipoAlocacao.Sigla
                };
            }

            return View(tipoAlocacaoModel);
        }

        [HttpPost, Route("tipoalocacao/create/{id=0}", Name = "PostTipoAlocacao")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TipoAlocacaoModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.IdTipoAlocacao == 0)
                    {
                        _tipoAlocacaoService.Incluir(model);

                        ExibirMensagem("Tipo alocação cadastrada com sucesso!!", Alert.success);
                    }
                    else
                    {
                        _tipoAlocacaoService.Editar(model);

                        ExibirMensagem("Tipo alocação alterada com sucesso!!", Alert.success);
                    }
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, Alert.danger);
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int id)
        {
            try
            {
                _tipoAlocacaoService.Deletar(id);

                ExibirMensagem("Registro excluído com Sucesso.", Alert.success);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, Alert.danger);
                return RedirectToAction("Index");
            }
        }
    }
}

SQH.MapaDeAlocacao/Views/Shared/_Alerts.cshtml
@foreach (string key in Enum.GetNames(typeof(SQH.Shared.Enums.Alerts.Alert)))
{
    if (Convert.ToString(TempData["Type"]).Equals(key))
    {
        <div class="alert alert-@key alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>@TempData["msg"]</strong>
        </div>
    }
}

SQH.MapaDeAlocacao/Views/Shared/_AlocacaoProjeto.cshtml
@model SQH.Entities.Models.Alocacao.AlocacaoRecursoModel

<!-- Modal -->
<div class="modal fade" id="@Model.IdAlocacao" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmar exclusão</h4>
            </div>
            <div class="modal-body">
                <form asp-controller="AlocacaoController" asp-action="CreateAlocacaoRecurso" method="post">
                    <input type="hidden" asp-for="IdAlocacao" id="hdnIdAlocacao" />
                    <input type="hidden" asp-for="IdRecurso" id="hdnIdRecurso" />

                    @*<input type="datetime" asp-for="DataInicio" id="DataInicio" />

                    <input type="datetime" asp-for="DataFinal" id="DataFinal" />*@

                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-default" data-dismiss="modal">Gravar</button>
                </form>
            </div>
            <div class="modal-footer">
                
            </div>
        </div>
    </div>
</div>

SQH.MapaDeAlocacao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SQH.MapaDeAlocacao</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link href="~/lib/jquery/dist/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/lib/DataTables-1.10.16/css/datatables.min.css" rel="stylesheet" />
    <link href="~/lib/DataTables-1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link href="~/lib/pace/css/pace-theme-minimal.css" rel="stylesheet" />

    @RenderSection("Styles", required: false)

</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SQH.MapaDeAlocacao</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Recurso" asp-action="Index">Recurso</a></li>
                        <li><a asp-area="" asp-controller="TipoAlocacao" asp-action="Index">Tipo de Alocação</a></li>
                        <li><a asp-area="" asp-controller="Projeto" asp-action="Index">Projeto</a></li>
                        <li><a asp-area="" asp-controller="MapaAlocacao" asp-action="Index">Mapa de Alocação</a></li>
                    </ul>
                </div>
            </div>
        </nav>

    }

    <div class="container body-content">
        @{Html.RenderPartial("_Alerts");}
        @RenderBody()
        <hr />

        @if (User.Identity.IsAuthenticated)
        {
            <footer>
                <p>&copy; 2018 - SQH.MapaDeAlocacao</p>
            </footer>
        }
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery/dist/jquery-ui.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/DataTables-1.10.16/js/datatables.min.js"></script>
        <script src="~/lib/DataTables-1.10.16/js/dataTables.bootstrap4.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.1/moment.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.1/locale/pt-br.js"></script>
        <script src="~/lib/datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/lib/pace/js/pace.min.js"></script>
        <script src="~/app/componentes.js"></script>
        <script src="~/js/methodsValitade.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/app/js/Recurso/CreateRecurso.js"></script>
        <script src="~/app/js/Recurso/EditRecurso.js"></script>
        <script src="~/app/js/Recurso/IndexRecurso.js"></script>
        <script src="~/app/js/Projeto/EditProjeto.js"></script>
        <script src="~/app/js/Projeto/IndexProjeto.js"></script>
        <script src="~/app/js/TipoAlocacao/IndexTipoAlocacao.js"></script>
        <script src="~/app/js/MapaAlocacao/MapaAlocacao.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="~/lib/jquery/dist/jquery-ui.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/lib/DataTables-1.10.16/js/datatables.min.js"></script>
        <script src="~/lib/DataTables-1.10.16/js/dataTables.bootstrap4.min.js"></script>
        <script src="~/lib/datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/lib/pace/js/pace.min.js"></script>
        <script src="~/app/componentes.js"></script>
        <script src="~/js/methodsValitade.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/app/app.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

SQH.MapaDeAlocacao/Views/Shared/_Modal.cshtml
@model DeletarViewModel
<!-- Modal -->
<div class="modal fade" id="@Model.Id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmar exclusão</h4>
            </div>
            <div class="modal-body">
                Você tem certeza que deseja deletar o registro: <span><b>@Model.Nome</b></span>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                @if (!String.IsNullOrEmpty(Model.Redirecionar))
                {
                    <a asp-action="Delete" asp-controller="@Model.Controller" asp-route-id="@Model.Id" asp-route-redirecionar="@Model.Redirecionar" title="Deletar" class="btn btn-danger">
                        Deletar
                    </a>
                }
                else
                {
                    <a asp-action="Delete" asp-controller="@Model.Controller" asp-route-id="@Model.Id" title="Deletar" class="btn btn-danger">
                        Deletar
                    </a>
                }
            </div>
        </div>
    </div>
</div>